---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(readxl)
```

```{r}
# loading dataset for the research proposal
df <- read_excel("Data1.xlsx")
```

```{r}
df$Annual_income_and_SWP <- df$Annual_income_and_SWP *1000
df$SWP <- df$SWP * 100
df
```

```{r}
library(dplyr)
df%>%
  mutate(Education=case_when(
    .$Education=="High School or GED" ~ 1,
    .$Education=="Some highschool" ~ 1,
    .$Education=="Completed Undergraduate" ~ 2,
    .$Education=="Some Undergraduate" ~ 2,
    .$Education=="Completed Masters" ~ 3,
    .$Education=="Some Maters" ~ 3,
    .$Education=="Some Phd" ~ 4,
    .$Education=="Completed Phd" ~ 4
    )) -> df
```

```{r}
df%>%
  mutate(Age=case_when(
    .$Age =="18-29" ~ 1,
    .$Age =="30-44" ~ 2,
    .$Age =="45-60" ~ 3,
    .$Age =="Greater than 60" ~ 4
    )) -> df
```

```{r}
df%>%
  mutate(Household_Income=case_when(
    .$Household_Income =="$0-$9,999" ~ 1,
    .$Household_Income =="$10,000-$24,999" ~ 2,
    .$Household_Income =="$25,000-$49,999" ~ 3,
    .$Household_Income =="$50,000-$74,999" ~ 4,
    .$Household_Income =="$75,000-$99,999" ~ 5,
    .$Household_Income =="$100,000-$124,999" ~ 6,
    .$Household_Income =="$125,000-$149,999" ~ 7,
    .$Household_Income =="$150,000-$174,999" ~ 8,
    .$Household_Income =="$175,000-$199,999" ~ 9,
    .$Household_Income =="$200,000+" ~ 10,
    .$Household_Income =="Prefer not to answer" ~ 996
    )) -> df
```

```{r}
df1 <- df
```

```{r}
df1$SWP[df1$SWP != 0] <- 1
df1
```

```{r}
m1 <- glm(SWP ~. ,data = df1)
summary(m1)
```

```{r}
m2 <- glm(SWP ~ Education + Own_computer + days_hospitalized + Disabled + Internet_access + Live_with_parents + Length_of_resume_gap_month + Annual_income_and_SWP + Unemployed + Read_books + Times_hospitalized + Age + Household_Income,data = df1)
summary(m2)
```

```{r}
m3 <- glm(SWP ~ Education + days_hospitalized + Disabled + Internet_access + Live_with_parents + Length_of_resume_gap_month + Annual_income_and_SWP + Unemployed + Read_books + Times_hospitalized + Age + Household_Income, data = df1)
summary(m3)
```

```{r}
m3.1 <- glm(SWP ~ Education + days_hospitalized + Disabled + Internet_access + Live_with_parents + Length_of_resume_gap_month + Annual_income_and_SWP + Unemployed + Read_books + Age + Household_Income,data = df1)
summary(m3.1)
```

```{r}
m4 <- glm(SWP ~ Education + Disabled + Internet_access + Live_with_parents + Length_of_resume_gap_month + Annual_income_and_SWP + Unemployed + Read_books + Times_hospitalized + Age + Household_Income,data = df1)
summary(m4)
```

```{r}
m5 <- glm(SWP ~ Education + Disabled + Internet_access + Length_of_resume_gap_month + Annual_income_and_SWP + Unemployed + Read_books + Times_hospitalized + Age + Household_Income,data = df1)
summary(m5)
```

```{r}
m6 <- glm(SWP ~ Education + Disabled + Internet_access + Annual_income_and_SWP + Unemployed + Read_books + Times_hospitalized + Age + Household_Income, data = df1)
summary(m6)
```

```{r}

```

